// data/medicationsData.ts
export const medications = [
    { name: "Abilify" },
    { name: "Actos" },
    { name: "Acyclovir" },
    { name: "Adderall" },
    { name: "Allopurinol" },
    { name: "Ambien" },
    { name: "Amitriptyline" },
    { name: "Amoxicillin" },
    { name: "Atenolol" },
    { name: "Ativan" },
    { name: "Azithromycin" },
    { name: "Baclofen" },
    { name: "Bactrim" },
    { name: "Benadryl" },
    { name: "Benzonatate" },
    { name: "Bupropion" },
    { name: "Buspirone" },
    { name: "Celecoxib" },
    { name: "Cialis" },
    { name: "Citalopram" },
    { name: "Clindamycin" },
    { name: "Concerta" },
    { name: "Cyclobenzaprine" },
    { name: "Cymbalta" },
    { name: "Depakote" },
    { name: "Dicyclomine" },
    { name: "Dilaudid" },
    { name: "Effexor" },
    { name: "Emgality" },
    { name: "Flagyl" },
    { name: "Fluoxetine" },
    { name: "Gabapentin" },
    { name: "Hydrochlorothiazide" },
    { name: "Hydrocodone-Acetaminophen" },
    { name: "Hydroxyzine" },
    { name: "Ibuprofen" },
    { name: "Keppra" },
    { name: "Levothyroxine" },
    { name: "Lexapro" },
    { name: "Lisinopril" },
    { name: "Lorazepam" },
    { name: "Losartan" },
    { name: "Macrobid" },
    { name: "Meloxicam" },
    { name: "Methadone" },
    { name: "Methocarbamol" },
    { name: "Methylprednisolone" },
    { name: "Metronidazole" },
    { name: "Morphine" },
    { name: "Nortriptyline" },
    { name: "Oxycontin" },
    { name: "Pantoprazole" },
    { name: "Percocet" },
    { name: "Phentermine" },
    { name: "Plaquenil" },
    { name: "Plavix" },
    { name: "Pradaxa" },
    { name: "Pravastatin" },
    { name: "Prednisone" },
    { name: "Pregabalin" },
    { name: "Promethazine" },
    { name: "Risperdal" },
    { name: "Ritalin" },
    { name: "Savella" },
    { name: "Seroquel" },
    { name: "Simvastatin" },
    { name: "Synthroid" },
    { name: "Tramadol" },
    { name: "Trazodone" },
    { name: "Trulicity" },
    { name: "Victoza" },
    { name: "Wellbutrin" }
  ];
  
  // data/supplementsData.ts
export const supplements = [
  "5-Htp",
  "Activated Charcoal",
  "Ashwagandha",
  "Astaxanthin",
  "Astragalus",
  "Berberine",
  "Biotin",
  "Bromelain",
  "Calcium",
  "Chlorella",
  "Chlorophyll",
  "Choline",
  "Chromium",
  "Coconut Oil",
  "Cod Liver Oil",
  "Colloidal Silver",
  "Conjugated Linoleic Acid",
  "Cordyceps",
  "Creatine",
  "Damiana",
  "Echinacea",
  "Emu Oil",
  "Evening Primrose Oil",
  "Fenugreek",
  "Fish Oil",
  "Folic Acid",
  "Gamma-Aminobutyric Acid",
  "Garlic",
  "Ginger",
  "Ginkgo",
  "Glucomannan",
  "Glutathione",
  "Gotu Kola",
  "Holy Basil",
  "Horny Goat Weed",
  "Hyaluronic Acid",
  "Inositol",
  "Iodine",
  "Iron",
  "Krill Oil",
  "L-Arginine",
  "L-Carnitine",
  "Lecithin",
  "Lemon Balm",
  "Licorice",
  "Lutein",
  "Maca",
  "Magnesium",
  "Maritime Pine",
  "Melatonin",
  "Moringa",
  "Oolong Tea",
  "Phenylalanine",
  "Phosphatidylserine",
  "Potassium",
  "Progesterone",
  "Propolis",
  "Pu-Erh Tea",
  "Quercetin",
  "Raspberry Ketone",
  "Rhodiola",
  "Royal Jelly",
  "Saw Palmetto",
  "Serrapeptase",
  "Slippery Elm",
  "Taurine",
  "Tea Tree Oil",
  "Tribulus",
  "Valerian",
  "Vitamin A",
  "Vitamin D",
  "Vitamin E",
  "Whey Protein",
  "Witch Hazel",
  "Xylitol",
  "Yohimbe",
];
export const articles = [
  {
    title: "Popular Weight Loss Drugs Raise Risk of More Stomach Trouble",
    source: "WebMD Health News",
  },
  {
    title: "FDA Adds Warning of Intestinal Blockages to Ozempic Label",
    source: "WebMD Health News Brief",
  },
  {
    title: "Popular OTC Decongestants Don’t Really Work, FDA Says",
    source: "WebMD Health News Brief",
  },
  {
    title: "3D-Printed Meds Customize the Dose for Sick Children",
    source: "WebMD Health News Brief",
  },
];

